version: '3.3'
services:
  web:
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - mongo
    environment:
    - MONGO_URI=mongodb://mongodb/book
    networks:
      - samplenet
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      samplenet:
        aliases:
          - "mongodb"
volumes:
  mongodb:
networks:
  samplenet:
    driver: bridge